# Generated by Django 4.2.7 on 2023-11-25 23:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0002_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("date_added",)},
        ),
        migrations.RenameField(
            model_name="message",
            old_name="data_added",
            new_name="date_added",
        ),
    ]
