# Generated by Django 4.2.7 on 2023-11-25 23:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0003_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RemoveField(
            model_name="message",
            name="date_added",
        ),
    ]
