# Generated by Django 4.2.7 on 2023-11-25 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0004_alter_message_options_remove_message_date_added"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ("date_added",)},
        ),
        migrations.AddField(
            model_name="message",
            name="date_added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
