# Generated by Django 4.2.7 on 2023-11-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("room", "0005_alter_message_options_message_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(),
        ),
    ]
